### ISSUE TITLE
Wrong $plugin->requires version

### ISSUE THREAD

**Issue by luisdev** [justinhunt/moodle-mod_newmodule#1]
version.php in this newmodule plugin shows that:

`$plugin->requires = 2010031900;`

Version 2010031900 is Moodle release 2.0 DEV – a development version of Moodle 2.0.

This plugin contains code for Scheduled Tasks (e.g. \pairwork\classes\task\pairwork_scheduled.php). Scheduled Tasks were a new feature added in Moodle 2.7, so presumably that $plugin->requires line should actually point to a version of Moodle 2.7, e.g.:

`$plugin->requires = 2014051200.00;`

Is that correct?

**Comment by justinhunt** [comment]
Yes you are correct. The newmodule is based on the original newmodule template ( https://github.com/moodlehq/moodle-mod_newmodule  )updated as I need to and I massaged it a little for the MB4D course (from memory). I generally decide at the release of the project which version of Moodle I need to support and alter the "requires" field accordingly. 

I will fix this up.

**Comment by justinhunt** [comment]
Thanks. I fixed this up now.
