### ISSUE TITLE
newmodule still uses the deprecated error() function.

### ISSUE THREAD

**Issue by luisdev** [justinhunt/moodle-mod_newmodule#2]
Line 46 in view.php calls the error() function:

```
if ($id) {
...
} elseif ($n) {
...
} else {
    error('You must specify a course_module ID or an instance ID');
}
```

This triggers a _"Debug info: error() is a deprecated function, please call print_error() instead of error()"_ message. 

The error message is also hardcoded into the code. This should be moved into a language string.
So I think the code could be updated with something like:

```
} else {
--    error('You must specify a course_module ID or an instance ID');
++    print_error('missingiderror', '@@newmodule@@');
}
```

where 'missingiderror' is a language string that's been defined in /moodle-mod_newmodule/lang/en/NEWMODULE.php. Example:

```
$string['defaultsettings'] ='Default Settings'; 
$string['exceededattempts'] ='You have completed the maximum {$a} attempts.'; 
$string['newmoduletask'] ='newmodule Task'; 
++    $string['missingiderror'] = 'You must specify a course_module ID or an instance ID';
```

**Comment by justinhunt** [comment]
Thanks Luis

I will do some work on the module very soon and will make this change.

Justin

**Comment by justinhunt** [comment]
Thanks for the error reports. I have fixed them up now  .. I hope
