### ISSUE TITLE
global $CFG,$DB; is repeated in lib.php

### ISSUE THREAD

**Issue by luisdev** [justinhunt/moodle-mod_newmodule#3]
Line 336 in moodle-mod_newmodule/lib.php defines the @@newmodule@@_is_complete() function.

Line 337 declares 
`global $CFG,$DB;` 

That global declaration is then duplicated again on line 339. Is this necessary?

```
336 function @@newmodule@@_is_complete($course,$cm,$userid,$type) { 
337      global $CFG,$DB; 
338       
339       global $CFG,$DB; 
340  
341     // Get module object 
```

**Comment by justinhunt** [comment]
Thanks this is fixed now.
